//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.Matriculas = new HashSet<Matricula>();
        }
    
        public int Id_Alumno { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Egreso { get; set; }
        public string Titulo_Admision { get; set; }
        public string Procedencia { get; set; }
        public string Reconocimiento_Año { get; set; }
        public Nullable<System.DateTime> Fecha_Acta_Grado { get; set; }
        public string Nro_Acta_Grado { get; set; }
        public string Denominacion_T { get; set; }
        public Nullable<System.DateTime> Fecha_Refrendacion { get; set; }
        public string Nro_Refrendacion { get; set; }
        public string Nom_Proyecto_T { get; set; }
        public Nullable<int> Id_Persona { get; set; }
    
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matricula> Matriculas { get; set; }
    }
}
