//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Distribucion()
        {
            this.Matricula_Asignatura = new HashSet<Matricula_Asignatura>();
        }
    
        public int Cod_Distribucion { get; set; }
        public Nullable<int> Cod_Semestre { get; set; }
        public Nullable<int> Id_Docente { get; set; }
        public Nullable<int> Cod_Asignatura { get; set; }
        public Nullable<int> Contador { get; set; }
        public Nullable<int> Cod_Periodo { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Semestre Semestre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matricula_Asignatura> Matricula_Asignatura { get; set; }
    }
}
