//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matricula()
        {
            this.Matricula_Asignatura = new HashSet<Matricula_Asignatura>();
        }
    
        public int Cod_Matricula { get; set; }
        public int Cod_Semestre { get; set; }
        public int Id_Alumno { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public int Cod_Periodo { get; set; }
        public string Observaciones { get; set; }
        public string Tipo { get; set; }
        public int Codigo { get; set; }
        public string Valor { get; set; }
        public bool Cancelado { get; set; }
        public Nullable<int> Credito { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matricula_Asignatura> Matricula_Asignatura { get; set; }
        public virtual Semestre Semestre { get; set; }
    }
}
