//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Alumnoes = new HashSet<Alumno>();
        }
    
        public int Id_Persona { get; set; }
        public string Nombres { get; set; }
        public string Apellido_1 { get; set; }
        public string Apellido_2 { get; set; }
        public string Cedula { get; set; }
        public string Genero { get; set; }
        public string Direccion { get; set; }
        public string Telefono_D { get; set; }
        public string Telefono_C { get; set; }
        public string Nacionalidad { get; set; }
        public string Provincia_Nac { get; set; }
        public string Canton_Nac { get; set; }
        public string Parroquia_Nac { get; set; }
        public Nullable<System.DateTime> Fecha_Nac { get; set; }
        public string Email { get; set; }
        public string PaisCodigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumno> Alumnoes { get; set; }
        public virtual Pai Pai { get; set; }
    }
}
